### ISSUE TITLE
非常棒

### ISSUE THREAD

**Issue by shiyiyan** [lixucuhk/adversarial-attack-on-GMM-i-vector-based-speaker-verification-systems#1]
老哥好，刚刚拜读了你的论文，非常棒，可否代码上传下，复现下结果

**Comment by lixucuhk** [comment]
你好！
十分感谢老铁的支持！ 我会在这周内将代码上传，欢迎指导，嘿嘿！
如果对你的科研工作有帮助，还请老铁在相关的工作中cite一下哈！
相互学习，共同进步！

**Comment by lixucuhk** [comment]
已上传，欢迎指正。
