### ISSUE TITLE
How can I  get the audio file for spoofing?

### ISSUE THREAD

**Issue by zxynbnb** [lixucuhk/adversarial-attack-on-GMM-i-vector-based-speaker-verification-systems#2]

**Comment by zxynbnb** [comment]
Dear author,
I noticed that the codes operate on features when spoofing. What if I want to listen to the adversarial audio?

**Comment by lixucuhk** [comment]
> Dear author,
> I noticed that the codes operate on features when spoofing. What if I want to listen to the adversarial audio?

Some adversarial features are converted back to audios, e.g. LPMS, please refer to [https://lixucuhk.github.io/adversarial-samples-attacking-ASV-systems/](url) to listen adversarial audios. Thanks for your interest!!!

**Comment by zxynbnb** [comment]
Thanks, I have found those audios. How can I  generate them from features?

**Comment by lixucuhk** [comment]
> Thanks, I have found those audios. How can I generate them from features?

Please look into the script **i-vector-lpms/local/gen_adv_wav.py** , which illustrates how to convert LPMS features back into audios.
