### ISSUE TITLE
内存溢出问题

### ISSUE THREAD

**Issue by zxynbnb** [lixucuhk/adversarial-attack-on-GMM-i-vector-based-speaker-verification-systems#3]
在extract_lpc.py文件中，write_matrix函数中的文件读写操作似乎会引起内存溢出问题，我用65G内存的电脑产生了这个问题。这是否是一个BUG？

**Comment by lixucuhk** [comment]
你好！由于提取feature的过程采取的是并行操作，所以对内存的需求比较大。建议你可以尝试减少num_workers的数值，或者采用单线程的操作提取特征，来减小内存的消耗。这里不是BUG。
谢谢！

**Comment by zxynbnb** [comment]
谢谢您的解答！

**Comment by muzihuole** [comment]
> 谢谢您的解答！
您好，您的问题解决了吗？我将num_workers的数值改成1，还是会发生内存溢出的情况，您知道怎么改写代码采用单线程的操作提取特征吗？谢谢啦
