### ISSUE TITLE
Which receipe of kaldi is used ?

### ISSUE THREAD

**Issue by GolferChen** [lixucuhk/adversarial-attack-on-GMM-i-vector-based-speaker-verification-systems#4]
Hello, thanks for releasing the code.

I am currently trying to reproduce the white box attack result of **iv-mfcc**.

My question is which receipe of kaldi is used.

According to my experience on Kaldi, it seems that **kaldi_root/egs/voxceleb/v1** is used. 

However, I did not see **LDA dimenison reduction**  in your code, which is used by **kaldi_root/egs/voxceleb/v1**.

Thanks a lot.

**Comment by lixucuhk** [comment]
Yeah, you are right. Kaldi scripts have LDA dimension reduction, but I skipped that function for simplicity when computing backward gradients. In my latter works, I added it into the system and verified that the LDA dimension reduction still cannot prevent systems from being attacked. Hope this can meet your queries.
Thank you!

**Comment by GolferChen** [comment]
Ok. Thanks for your reply.
In fact, I agree with you since LDA dimension reduction is totally differentiable.
