### ISSUE TITLE
内存溢出问题

### ISSUE THREAD

**Issue by muzihuole** [lixucuhk/adversarial-attack-on-GMM-i-vector-based-speaker-verification-systems#6]
你好，我在运行i-vector-lpms时，当进行到stage1，extract LPMS features, and generate VAD files时内存占用过大，造成内存溢出，我将run.sh中num_workers改为1，extras_lps.py中的args.num_workers也改为1，运行之后，还是会造成内存溢出，您知道怎么解决这个问题吗？
我看您之前说将num_workers改成1，我试了下不行，您还说可以将它改成单线程操作，我不太懂怎么改成单线程，能麻烦您附下单线程的代码吗？谢谢您！期待您的答复。

**Comment by lixucuhk** [comment]
谢谢您对我们工作的关注！单线程的操作我指的就是将num_workers设为1。
目前的版本是将生成的特征存入内存，集体写入kaldi的ark文件。如果您的内存比较小，建议可以先保存生成的特征为numpy格式，后面再依次读取numpy文件，写入ark文件中。谢谢！

**Comment by muzihuole** [comment]
好的，非常感谢您的回复！我去尝试一下。

**Comment by muzihuole** [comment]
您好，方便说一下您所使用的机器配置吗？CPU、内存、显卡、硬盘等
